server:
  port: 8085
  servlet.context-path: /

spring:
  application:
    name: me-consumer-cloud
  cloud:
    consul:
      host: 10.82.12.238
      port: 8503
      discovery:
        prefer-ip-address: true
        health-check-interval: 10s
        healthCheckPath: ${server.servlet.context-path}/health
        instanceId: ${spring.application.name}:${server.port}:${random.value}:${random.int[1,1000000]}
        
es.addr: 10.82.12.67:9200

me:
  platformId: 1
  adapter:
    - {tableName: user, index: user, refactor: true, mapping: '{"id": "long", "name": "keyword", "password": "keyword", "email": "keyword", "age": "integer"}'}
    - {tableName: bbb, index: bbb, refactor: false, mapping: '{"id": "long"}'}
